AUTHOR:
  NAME: '陳放為'
  GITHUB: 'fwchen'

BLOG:
  BLOGDIR: 'articles'
  NAME: '陈放为的博客'
  DESC: 'And the Chamber of Secrets'
  TMPDIR: '/tmp'
  TMPNAME: 'WIngTmp'
  PORT: 8080
  HOST: '127.0.0.1'
  INDEX_ARTICLE_NUMBER: 7
  CATEGORY_ARTICLE_NUMBER: 20
  ALL_PAGE_ARTICLE_NUMBER: 20
  SORT_ARTICLE_BY: 'create'
  ARTICLE_SUMMARY_CHAR_NUMBER: 300

STYLE:
  THEMEDIR: '@themes'
  THEME: 'hg'
  THEME_CONFIG_FILE: 'theme.config.yaml'

SERVE:
  HOST: '0.0.0.0'
  PORT: '8080'

MAPPING:
  '@root-asset/*': '/'
  '@demo': '/demo/'

LANG: 'zh-CN'

SSR:
  IGNORE:
    - '^/demo'
    - '/google281a0d5aa47339e0.html'
