AUTHOR:
  NAME: '陳放為'
  GITHUB: 'fwchen'

BLOG:
  ARTICLES_DIR: 'articles'
  HTTPS: true
  DOMAIN: 'www.chencanhao.com'
  NAME: '陈放为的博客'
  DESC: 'And the Chamber of Secrets'
  PORT: 8079
  HOST: 'www.chencanhao.com'
  INDEX_ARTICLE_NUMBER: 7
  CATEGORY_ARTICLE_NUMBER: 20
  ALL_PAGE_ARTICLE_NUMBER: 20
  SORT_ARTICLE_BY: 'create'
  ARTICLE_SUMMARY_CHAR_NUMBER: 300
  IGNORE_CATEGORY_RENDER: true

STYLE:
  THEMEDIR: 'node_modules/@starfishx'
  # THEME: 'starfish-theme-hg'
  THEME: 'theme-hg'
  THEME_CONFIG_FILE: 'theme.config.yaml'

SERVE:
  HOST: '0.0.0.0'
  PORT: '8080'

MAPPING:
  '@root-asset/*': '/'
  '@demo': '/demo/'

LANG: 'zh-CN'

SSR:
  IGNORE:
    - '^/demo'
    - '/google281a0d5aa47339e0.html'
