
AUTHOR:
  NAME: '陳放為'
  GITHUB: 'AbyChan'

BLOG:
  NAME: '陈放为的博客'
  TMPDIR: '/tmp'
  TMPNAME: 'WIngTmp'
  PORT: 8080
  HOST: '127.0.0.1'
  INDEX_ARTICLE_NUMBER: 7
  SORT_ARTICLE_BY: 'create'

STYLE:
  THEME: 'white-card'
  