
AUTHOR:
  NAME: '陳放為'
  GITHUB: 'AbyChan'

BLOG:
  NAME: '陈放为的博客'
  DESC: 'And the Chamber of Secrets'
  TMPDIR: '/tmp'
  TMPNAME: 'WIngTmp'
  PORT: 8080
  HOST: '127.0.0.1'
  INDEX_ARTICLE_NUMBER: 7
  CATEGORY_ARTICLE_NUMBER: 20
  ALL_PAGE_ARTICLE_NUMBER: 20
  SORT_ARTICLE_BY: 'create'
  ARTICLE_SUMMARY_CHAR_NUMBER: 300


STYLE:
  THEMEDIR: '@themes'
  THEME: 'hg'

SERVE:
  HOST: '0.0.0.0'
  PORT: '8080'

MAPPING:
  '@image': '/static/img/'
  '@root-asset': '/'
  '@demo': '/demo/'

LANG: 'zh-CN'
